insert into Homework (description) values ('Eucalyptus');
insert into Homework (description) values ('Doxycycline Hyclate');
insert into Homework (description) values ('passalora fulva');
insert into Homework (description) values ('Helminthosporium');
insert into Homework (description) values ('Mouse Epithelium');
insert into Homework (description) values ('Ranitidine');
insert into Homework (description) values ('Cocoa butter, Phenylephrine HCl, Shark liver oil');
insert into Homework (description) values ('sodium chloride');
insert into Homework (description) values ('Metformin Hydrochloride');
insert into Homework (description) values ('Acetaminophen, Aspirin, and Caffeine');
insert into Homework (description) values ('Ranitidine');
insert into Homework (description) values ('nystatin');
insert into Homework (description) values ('Ferrum sidereum Sulfur');
insert into Homework (description) values ('Tag Alder');
insert into Homework (description) values ('Dextromethorphan Hydrobromide / Guaifenesin');
insert into Homework (description) values ('CEFOTAXIME');
insert into Homework (description) values ('Aluminum Zirconium Tetrachlorohydrex GLY');
insert into Homework (description) values ('ETHYLHEXYL METHOXYCINNAMATE, Zinc Oxide, Ethylhexy Salicate, TITANUIM DIOXIDE, Bis-ethylhexyloxyphenol methoxyphenyl triazine');
insert into Homework (description) values ('TIROFIBAN');
insert into Homework (description) values ('Oxycodone Hydrochloride');
insert into Homework (description) values ('ibuprofen');
insert into Homework (description) values ('CALCIUM CITRATE, CALCIUM CARBONATE, POTASSIUM IODIDE, MAGNESIUM CITRATE, ZINC CITRATE, COPPER GLUCONATE, and FERROUS FUMARATE');
insert into Homework (description) values ('Aceticum Ac, Anacard Or, Baryta Iod, Calc Carb, Capsicum, Fucus, Graphites,, Nat Sulphuricum, Phytolacca, Stannum Met, Thyroidinum, Zinc Met.');
insert into Homework (description) values ('CANDIDA ALBICANS');
insert into Homework (description) values ('Ragweed Slender');
insert into Homework (description) values ('IMIPENEM and CILASTATIN SODIUM');
insert into Homework (description) values ('ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY');
insert into Homework (description) values ('oseltamivir phosphate');
insert into Homework (description) values ('Alcohol');
insert into Homework (description) values ('MENTHOL');
insert into Homework (description) values ('UNDECYLENIC ACID');
insert into Homework (description) values ('olmesartan medoxomil and hydrochlorothiazide');
insert into Homework (description) values ('Octinoxate');
insert into Homework (description) values ('vigabatrin');
insert into Homework (description) values ('Ondansetron');
insert into Homework (description) values ('Cisplatin');
insert into Homework (description) values ('DIGOXIN');
insert into Homework (description) values ('Lidocaine Hydrochloride');
insert into Homework (description) values ('Nicotine Polacrilex');
insert into Homework (description) values ('Fluocinonide');
insert into Homework (description) values ('APIS MELLIFICA');
insert into Homework (description) values ('Cetirizine HCl, Pseudoephedrine HCl');
insert into Homework (description) values ('OCTINOXATE');
insert into Homework (description) values ('Phenol');
insert into Homework (description) values ('Salicylic Acid');
insert into Homework (description) values ('Warfarin Sodium');
insert into Homework (description) values ('doxycycline hyclate');
insert into Homework (description) values ('Tolnaftate');
insert into Homework (description) values ('dexamethasone');
insert into Homework (description) values ('Lansoprazole');
insert into Homework (description) values ('Chlophedianol HCL, Chlorpheniramine Maleate and Phenylephrine HCl');
insert into Homework (description) values ('Tramadol Hydrochloride');
insert into Homework (description) values ('Phenylephrine HCl');
insert into Homework (description) values ('Alcohol');
insert into Homework (description) values ('ALCOHOL');
insert into Homework (description) values ('sodium fluoride');
insert into Homework (description) values ('METFORMIN HYDROCHLORIDE');
insert into Homework (description) values ('abacavir sulfate');
insert into Homework (description) values ('Epicoccum nigrum');
insert into Homework (description) values ('Acetaminophen and Diphenhydramine HCl');
insert into Homework (description) values ('SALICYLIC ACID');
insert into Homework (description) values ('DOG EPITHELIA');
insert into Homework (description) values ('Amoxicillin');
insert into Homework (description) values ('Triticum Cerebri');
insert into Homework (description) values ('cisatracurium besylate');
insert into Homework (description) values ('Nabumetone');
insert into Homework (description) values ('Tag Alder');
insert into Homework (description) values ('Cetirizine Hydrochloride');
insert into Homework (description) values ('Ibuprofen');
insert into Homework (description) values ('Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride');
insert into Homework (description) values ('Trazodone Hydrochloride');
insert into Homework (description) values ('Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone');
insert into Homework (description) values ('folltropin alfa');
insert into Homework (description) values ('Acetaminophen');
insert into Homework (description) values ('Codeine Phosphate, Pseudoephedrine Hydrochloride, Pyrilamine Maleate');
insert into Homework (description) values ('Aspirin');
insert into Homework (description) values ('Levocetirizine dihydrochloride');
insert into Homework (description) values ('Escitalopram');
insert into Homework (description) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into Homework (description) values ('MENTHOL');
insert into Homework (description) values ('Cacao Bean');
insert into Homework (description) values ('menthol');
insert into Homework (description) values ('Metronidazole');
insert into Homework (description) values ('Acetaminophen');
insert into Homework (description) values ('Octinoxate and Oxybenzone');
insert into Homework (description) values ('Penicilium chrysogenum');
insert into Homework (description) values ('Sodium fluoride');
insert into Homework (description) values ('PredniSONE');
insert into Homework (description) values ('desvenlafaxine');
insert into Homework (description) values ('Magesium Citrate');
insert into Homework (description) values ('Pyrilamine Maleate and Phenylephrine Hydrochloride');
insert into Homework (description) values ('Allantoin');
insert into Homework (description) values ('LOVASTATIN');
insert into Homework (description) values ('Wheat Stem Rust');
insert into Homework (description) values ('Titanium Dioxide and Octinoxate');
insert into Homework (description) values ('Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl');
insert into Homework (description) values ('Octinoxate and Titanium Dioxide');
insert into Homework (description) values ('Fluconazole');
insert into Homework (description) values ('Triamcinolone Acetonide');
insert into Homework (description) values ('Argentum Metallicum');
